# this file builds the docker image , tags the image with github commit hash 
# and pushes it to dockerhub 
# also this action will update the image tages of the kubernetes deployment repo

name : build docker image 
on : push

env:
  IMAGE_NAME: gocd-django
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}s

jobs:
  Build_and_push_docker :  
    runs-on : ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}


      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Docker logout
        uses: docker/logout-action@v1

