# this file builds the docker image , tags the image with github commit hash 
# and pushes it to dockerhub 
# also this action will update the image tages of the kubernetes deployment repo

name : build docker image 
on : 
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: gocd-django
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  USERNAME: ${{ secrets.USERNAME }}
  EMAIL: ${{ secrets.EMAIL }}


jobs:
  Build_and_push_docker :  
    runs-on : ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}


      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name : checkout k8s repository 
        uses : actions/checkout@master
        with :
          repository: nlrchudamani/GOCD-k8s@main
          token: ${{ secrets.PAT }}

      - name: Update the image name in the deployment file and push to k8s repository
        run: |
          cat "deployment.yaml.template" | sed "s/nlrcmani/gocd-django:latest/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}/g"
          git config --global user.name ${{ env.USERNAME }}
          git config --global user.email ${{ env.EMAIL }}
          git add -A
          git commit -m "commit message"
          git push
          
          

      